config/routes.rb
MyPodcasts::Application.routes.draw do
  root to: 'pages#index'

  namespace :admin do
    root to: 'pages#index'
    resources :podcasts, only: [:index, :edit, :update]
  end

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/:name' => 'users#show', as: :profile

  resources :users, only: [:show]
  resources :podcasts, only: [:show, :new, :create]
  resources :subscriptions, only: [:create, :update, :destroy]
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :name, :feed_url, :itunes_url, :logo, :created_by_id, :overview, :slug, :active

  validates :name, :created_by_id, :logo, :feed_url, :itunes_url, :overview, presence: true
  validates :name, :feed_url, :itunes_url, uniqueness: true
  validates :active, inclusion: { in: [true, false] }

  validate :different_urls_validation

  has_many :subscriptions
  belongs_to :created_by, class_name: 'User'

  before_validation :set_active

  has_attached_file :logo, styles: { logo: '300x300>', thumb: '24x24>' }
  validates_attachment :logo, size: { in: 0..2.megabytes }

  friendly_id :name, use: :slugged

  scope :actives, where(active: true)
  scope :not_actives, where(active: false)

  def score_average
    scores = self.subscriptions.pluck(:score).compact
    scores.blank? ? 0 : scores.inject{ |sum, el| sum + el }.to_f / scores.size
  end

  def self.ordered
   self.all.sort_by { |podcast| [podcast.score_average, podcast.subscriptions.count] }.reverse
  end

  private

  def set_active
    self.active = false if self.active.nil?
  end

  def different_urls_validation
    errors.add(:base, 'As URLs do feed e do iTunes não podem ser a mesma') if self.feed_url == self.itunes_url
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :user_id, :podcast_id, :score

  validates :user_id, :podcast_id, presence: true
  validates :user_id, uniqueness: { scope: :podcast_id }

  belongs_to :user
  belongs_to :podcast

  scope :actives, joins(:podcast).where(podcasts: {active: true}).includes(:podcast)
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :subscriptions

  attr_accessible :image_url

  validates :provider, :uid, :name, presence: true

  def self.from_omniauth(auth)
    user = where(auth.slice('provider', 'uid')).first

    if user
      user.update_attributes image_url: auth['info']['image'] unless user.image_url
      user
    else
      create_from_omniauth(auth)
    end
  end

  private

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider  = auth['provider']
      user.uid       = auth['uid']
      user.image_url = auth['image_url']
      user.name      = auth['info']['nickname']
    end
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_filter :authenticate

  private

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      @authenticated = username == Settings.authentication.username && password == Settings.authentication.password
    end
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::ApplicationController
  def index
  end
end

app/controllers/admin/podcasts_controller.rb
class Admin::PodcastsController < Admin::ApplicationController
  before_filter :load_podcast, only: [:edit]
  before_filter :load_users,   only: [:edit]

  def index
    @podcasts = Podcast.all
  end

  def edit
  end

  def update
    @podcast = Podcast.find params[:id]

    if @podcast.update_attributes params[:podcast]
      flash[:notice] = 'Podcast atualizado.'
      redirect_to admin_podcasts_path
    else
      flash.now[:alert] = @podcast.errors.full_messages.join(', ')
      load_users
      render :edit
    end
  end

  private

  def load_podcast
    @podcast = Podcast.find params[:id]
  end

  def load_users
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]).decorate if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    if current_user.blank?
      flash[:error] = 'Você precisa se logar antes de ver essa página!'
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @podcasts = Podcast.actives.ordered
    @users = current_user ? (User.order('RANDOM()') - [current_user.model]).map(&:decorate) : User.decorate
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]

  def show
    @podcast = Podcast.find params[:id]
    @subscribers = @podcast.subscriptions.map { |subscription| subscription.user.decorate }

    if current_user
      @subscription = current_user.subscriptions.where(podcast_id: @podcast.id).first || Subscription.new
    end
  end

  def new
    @podcast = Podcast.new
  end

  def create
    @podcast = Podcast.new params[:podcast]
    @podcast.created_by = current_user

    if @podcast.save
      Subscription.create podcast_id: @podcast.id, user_id: current_user.id
      flash[:notice] = 'Podcast cadastrado. Aguarde a aprovação do mesmo.'
      redirect_to @podcast
    else
      flash.now[:error] = @podcast.errors.full_messages.join(', ')
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url, notice: 'Logado com sucesso.'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @subscription = Subscription.new params[:subscription]
    @subscription.user = current_user

    @subscription.save
    redirect_to @subscription.podcast
  end

  def update
    @subscription = current_user.subscriptions.where(podcast_id: params[:subscription][:podcast_id]).first

    @subscription.update_attributes score: params[:subscription][:score]
    redirect_to @subscription.podcast
  end

  def destroy
    @subscription = Subscription.find params[:id]

    if @subscription.user == current_user
      @subscription.destroy
      redirect_to root_path
    else
      flash[:error] = 'Você não tem autorização para isso.'
      redirect_to @subscription.podcast
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.where(name: params[:name]).first.decorate
    @subscriptions = @user.subscriptions.actives.sort_by{ |subscription| [subscription.score.to_i, subscription.podcast.subscriptions.count] }.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/pages/index.haml
.well
  %h1 Admin

%table.table.table-striped
  %tbody
    %tr
      %td
        =link_to 'Podcasts', admin_podcasts_path

app/views/admin/podcasts/edit.haml
.well
  %h1=@podcast.name

=form_for [:admin, @podcast], html: { class: 'form-horizontal', multipart: true } do |f|
  .control-group
    =f.label :name, class: 'control-label'
    .controls
      =f.text_field :name, class: 'text_field'

  .control-group
    =f.label :slug, class: 'control-label'
    .controls
      =f.text_field :slug, class: 'text_field'

  .control-group
    =f.label :overview, class: 'control-label'
    .controls
      =f.text_area :overview, rows: 5, class: 'input-xxlarge'

  .control-group
    =f.label :feed_url, class: 'control-label'
    .controls
      =f.text_field :feed_url, class: 'text_field', class: 'input-xxlarge'

  .control-group
    =f.label :itunes_url, class: 'control-label'
    .controls
      =f.text_field :itunes_url, class: 'text_field', class: 'input-xxlarge'

  .control-group
    =f.label :active, class: 'control-label'
    .controls
      =f.select :active, [true, false], selected: @podcast.active?

  .control-group
    =f.label :logo, class: 'control-label'
    .controls
      -if @podcast.logo.present?
        =image_tag @podcast.logo.url(:logo)
        %br

      =f.file_field :logo, class: 'input-xlarge'
      %span.help-block Utilize uma imagem de tamanho 300 X 300px.

  .control-group
    =f.label :created_by_id, class: 'control-label'
    .controls
      =f.select :created_by_id, @users.map { |user| ["@#{user.name} (##{user.id})", user.id] }, selected: @podcast.created_by_id

  .form-actions
    =f.submit 'Salvar', class: 'btn btn-primary'
    =link_to 'Cancelar', admin_podcasts_path, class: 'btn'

app/views/admin/podcasts/index.haml
.well
  %h1 Podcasts

-if @podcasts.any?
  %table.table.table-striped
    %thead
      %tr
        %th &nbsp;
        %th Id
        %th Name
        %th Active
        %th Created at
        %th Creator
        %th &nbsp;

    %tbody
      -@podcasts.each do |podcast|
        %tr
          %td=image_tag podcast.logo.url(:thumb)
          %td=podcast.id
          %td=link_to podcast.name, podcast
          %td=podcast.active
          %td=l podcast.created_at, format: :short
          %td
            =link_to "@#{podcast.created_by.name}", profile_path(podcast.created_by.name)
            =link_to '(twitter)', "https://twitter.com/#{podcast.created_by.name}"
          %td=link_to 'Editar', edit_admin_podcast_path(podcast)

-else
  %p Nenhum podcast cadastrado.

app/views/layouts/application.haml
!!! 5
%html(lang='pt-BR')
  %head
    %meta(charset='utf-8')
    %meta(http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1')
    %meta(name='viewport' content='width=device-width, initial-scale=1.0')
    %title=content_for?(:title) ? "#{yield(:title)} - MyPodcasts.info" : 'MyPodcasts.info'
    -if content_for? :meta_description
      %meta{ name: 'description', content: yield(:meta_description) }
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      =javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js'
    =stylesheet_link_tag 'application', :media => 'all'
    %link(href='images/apple-touch-icon-144x144.png' rel='apple-touch-icon-precomposed' sizes='144x144')
    %link(href='images/apple-touch-icon-114x114.png' rel='apple-touch-icon-precomposed' sizes='114x114')
    %link(href='images/apple-touch-icon-72x72.png' rel='apple-touch-icon-precomposed' sizes='72x72')
    %link(href='images/apple-touch-icon.png' rel='apple-touch-icon-precomposed')
    =favicon_link_tag
    =csrf_meta_tags

  %body
    #fb-root
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target='.nav-collapse' data-toggle='collapse')
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          =link_to 'MyPodcasts.info', root_path, class: 'brand'
          .container.nav-collapse
            %ul.nav
              -if current_user
                %li
                  =link_to new_podcast_path do
                    %em.icon-volume-down
                    Incluir outros podcasts
            %ul.nav.pull-right
              -if current_user
                %li
                  =link_to profile_path(current_user.name) do
                    =current_user.twitter_photo
                    =current_user.name
                %li
                  =link_to signout_path do
                    %em.icon-off
                    Sair
              -else
                %li
                  =link_to '/auth/twitter' do
                    =image_tag 'twitter_icon.png'
                    Logar com o Twitter

    .container
      =bootstrap_flash
      =yield

    %footer
      %p="Copyright &copy; #{Date.today.year} Lucas Caton. Esse projeto é #{link_to 'open source', 'https://github.com/lucascaton/mypodcasts.info', target: '_blank'}.".html_safe
    =javascript_include_tag 'application'

    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-2643450-9']);
      _gaq.push(['_trackPageview']);

      (function(){
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "MyPodcasts"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") MyPodcasts
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/pages/index.haml
.row
  .span12
    .pull-right
      %a.twitter-share-button(href='https://twitter.com/share' data-lang='pt-BR' data-url='http://mypodcasts.info'
        data-via='mypodcastsinfo' data-text='Compartilhe os seus podcasts preferidos e descubra o que os seus amigos gostam de escutar!')
.row
  .span12
    .centered_text
      =image_tag 'logo_small.png'
    .well.centered_text
      %h3 Cadastre os seus podcasts preferidos, crie um perfil público para compartilhar os que você mais gosta através de notas e descubra o que os seus amigos gostam de escutar!
      .fb-like{ :'data-href' => 'https://www.facebook.com/mypodcasts', :'data-send' => 'false',
        :'data-layout' => 'button_count', :'data-width' => '450', :'data-show-faces' => 'true' }
.row
  .span6
    .well
      %h2 Usuários
      -if current_user || @users.any?
        %br
        %table#users_table.table.table-striped
          %tbody
            -([current_user] + @users).compact.each do |user|
              %tr{ class: user == current_user ? 'highlighted' : '' }
                %td.photo_and_name
                  =link_to user.twitter_photo, profile_path(user.name)
                  =link_to user.name, profile_path(user.name)
                %td
                  ="(#{ pluralize user.subscriptions.actives.count, 'podcast' })"

  .span6
    .well
      %h2 Podcasts
      -if @podcasts.any?
        %br
        %table.table.table-striped
          %tbody
            -@podcasts.each do |podcast|
              %tr
                %td
                  =link_to podcast do
                    =image_tag podcast.logo.url(:thumb)
                  ="#{link_to(podcast.name, podcast)} (#{ pluralize podcast.subscriptions.count, 'ouvinte' })".html_safe
                  .score_read_only{ 'data-score' => podcast.score_average }
                -if current_user
                  %td=render 'subscriptions/links', podcast: podcast,
                    subscription: current_user.subscriptions.where(podcast_id: podcast.id).first || Subscription.new

app/views/podcasts/new.haml
%h2 Cadastrar podcast
-# .alert
-#   %button.close(type='button' data-dismiss='alert') &times;
-#   %strong Atenção!
-#   Cadastre apenas podcasts que ainda
-#   %strong NÃO
-#   estiverem cadastrados!
%br

=form_for @podcast, html: { multipart: true, class: 'form-horizontal' } do |f|
  .control-group
    =f.label :name, class: 'control-label'
    .controls
      =f.text_field :name, class: 'input-xlarge'

  .control-group
    =f.label :overview, class: 'control-label'
    .controls
      =f.text_area :overview, rows: 5, class: 'input-xxlarge'

  .control-group
    =f.label :feed_url, class: 'control-label'
    .controls
      =f.text_field :feed_url, class: 'input-xxlarge'

  .control-group
    =f.label :itunes_url, class: 'control-label'
    .controls
      =f.text_field :itunes_url, class: 'input-xxlarge'

  .control-group
    =f.label :logo, class: 'control-label'
    .controls
      =f.file_field :logo
      %span.help-block Utilize uma imagem de tamanho 300 X 300px.

  .control-group
    .controls
      =f.submit 'Salvar', class: 'btn btn-primary btn-large', disable_with: 'Salvando...'
      %span.help-block * Campos obrigatórios.

app/views/podcasts/show.haml
-content_for(:title) { @podcast.name }
-content_for(:meta_description) { @podcast.overview.gsub("\n", ' ').html_safe }

-if @podcast.active?
  .row
    .span3
      =image_tag @podcast.logo.url(:logo)
      %br
      %br
      .centered_text.pop
        -if @podcast.feed_url.present?
          =link_to image_tag('feed.png'), @podcast.feed_url, target: '_blank',
            rel: 'popover', 'data-placement' => 'bottom',
            'data-original-title' => t('activerecord.attributes.podcast.feed_url'),
            'data-trigger' => 'hover', 'data-content' => 'Assine esse podcast através do seu leitor de feed'

        -if @podcast.itunes_url.present?
          =link_to image_tag('itunes.png'), @podcast.itunes_url, target: '_blank',
            rel: 'popover', 'data-placement' => 'bottom',
            'data-original-title' => t('activerecord.attributes.podcast.itunes_url'),
            'data-trigger' => 'hover', 'data-content' => 'Assine esse podcast através do iTunes'

      %br
      -if current_user
        %h3 Sua nota
        =form_for @subscription, html: { id: 'subscription_form' } do |f|
          =f.hidden_field :podcast_id, value: @podcast.id
          .centered-text
            #score{ 'data-score' => @subscription.score }
              =f.hidden_field :score
      %h3 Nota média
      .score_read_only_big{ 'data-score' => @podcast.score_average }
    .span9
      %h1=@podcast.name
      -if current_user
        =render 'subscriptions/links', podcast: @podcast, subscription: @subscription
      %br
      %br
      .well
        %p.podcast_overview=@podcast.overview.gsub(/\n/, '<br />').html_safe
      -if @subscribers.any?
        .well
          %h4="#{ pluralize @podcast.subscriptions.count, 'ouvinte' }:"
          %br
          %table.table.table-striped
            %tbody
              -@subscribers.each do |user|
                %tr
                  %td.photo
                    =link_to profile_path(user.name) do
                      =user.twitter_photo('normal')
                  %td
                    =link_to profile_path(user.name) do
                      %h4=user.name

-else
  %h2=@podcast.name
  %h3.muted Ainda não aprovado.

app/views/subscriptions/_links.haml
-if current_user
  -if subscription.new_record?
    =form_for subscription do |f|
      =f.hidden_field :podcast_id, value: podcast.id
      =f.button 'Incluir na minha lista', class: 'btn btn-success'
  -else
    =link_to 'Retirar da minha lista', subscription_path(subscription),
      method: :delete, class: 'btn btn-danger',
      confirm: 'Tem certeza que deseja retirar esse podcast da sua lista? Sua nota para esse podcast será perdida!'

app/views/users/show.haml
-content_for(:title) { "@#{@user.name}" }

.row
  .span3
    =@user.twitter_photo('original')
    %br
    %br
    .centered_text
      %h2="@#{@user.name}"
      %p="Membro desde #{l @user.created_at.to_date}"

  .span9
    .well
      -if @subscriptions.any?
        %h2="#{ pluralize @user.subscriptions.count, 'podcast' }"
        %table.table.table-striped
          %tbody
            -@subscriptions.each do |subscription|
              %tr
                %td
                  =link_to subscription.podcast do
                    =image_tag subscription.podcast.logo.url(:logo)
                %td
                  %h3="#{link_to(subscription.podcast.name, subscription.podcast)} (#{ pluralize subscription.podcast.subscriptions.count, 'ouvinte' })".html_safe
                  %h4 Nota do usuário
                  .score_read_only_big{ 'data-score' => subscription.score }
                  %h4 Nota média
                  .score_read_only_big{ 'data-score' => subscription.podcast.score_average }